version: "3"
services:
        mysql:
            image: mysql:5.7
            ports:
                - "5454:5454"
            volumes:
                - mysql_data:/var/lib/mysql
            environment:
                MYSQL_ROOT_PASSWORD: example
        wordpress:
            image: wordpress
            ports:
                - "8042:80"
            volumes:
                - mywebsite_data:/var/www/html
            environment:
                WORDPRESS_DB_PASSWORD: example
            depends_on:
                - mysql
            links:
                - mysql

volumes:
        mysql_data:
        mywebsite_data:
